// Chord-search regression wall.
//
// Table-driven coverage of the professional notation matrix from the WS13 audit
// (docs/superpowers/ws13-chord-search-audit.md). Every row was generated by
// EXECUTING the real parser, never by reading code. Three blocks:
//   1. POSITIVE  — notation → exact ChordQuality (incl. accidental roots, case,
//                  unicode, slash chords, single-word verbal, legit-complex).
//   2. NEGATIVE  — garbage / ambiguous input that must NOT parse (returns null).
//   3. COMPLEX   — chords only the algorithmic fallback handles; must still parse
//                  (non-null) so the garbage gate never over-rejects.
//
// If a future change regresses any cell, this wall fails.

import { describe, it, expect } from 'vitest';
import { parseChordSymbol } from '../chordParser';
import type { ChordQuality } from '../../types/music';

// ── 1. POSITIVE: notation → exact quality ──────────────────────────────────
// [notation, expectedQuality]
const POSITIVE: Array<[string, ChordQuality]> = [
  // major
  ['C', 'major'], ['CM', 'major'], ['Cmaj', 'major'], ['Cmajor', 'major'],
  ['C major', 'major'], ['Cmaj/E', 'major'], ['C/E', 'major'], ['C/G', 'major'],
  // minor
  ['Cm', 'minor'], ['Cmin', 'minor'], ['Cminor', 'minor'], ['C-', 'minor'],
  ['Cmi', 'minor'], ['C minor', 'minor'], ['Cm/Eb', 'minor'],
  // diminished
  ['Cdim', 'diminished'], ['C°', 'diminished'], ['Co', 'diminished'],
  ['Cdiminished', 'diminished'], ['C dim', 'diminished'],
  // augmented
  ['Caug', 'augmented'], ['C+', 'augmented'], ['Caugmented', 'augmented'],
  ['C aug', 'augmented'],
  // major6 — capital-M booby trap (CM6 must NOT become minor6)
  ['C6', 'major6'], ['Cmaj6', 'major6'], ['Cmajor6', 'major6'], ['CM6', 'major6'],
  ['C6/E', 'major6'], ['BM6', 'major6'],
  // minor6
  ['Cm6', 'minor6'], ['Cmin6', 'minor6'], ['Cminor6', 'minor6'], ['C-6', 'minor6'],
  ['Cmi6', 'minor6'],
  // major7
  ['Cmaj7', 'major7'], ['CM7', 'major7'], ['CΔ', 'major7'], ['CΔ7', 'major7'],
  ['Cma7', 'major7'], ['Cmajor7', 'major7'], ['C major 7', 'major7'],
  ['C maj7', 'major7'], ['Cmaj7/G', 'major7'], ['Cj7', 'major7'], ['Cj', 'major7'],
  // minor7
  ['Cm7', 'minor7'], ['Cmin7', 'minor7'], ['Cminor7', 'minor7'], ['C-7', 'minor7'],
  ['Cmi7', 'minor7'], ['Cmin7/Bb', 'minor7'], ['C minor 7', 'minor7'],
  // dominant7
  ['C7', 'dominant7'], ['Cdom7', 'dominant7'], ['Cdominant7', 'dominant7'],
  ['C7/E', 'dominant7'], ['C dominant 7', 'dominant7'], ['C dom7', 'dominant7'],
  // diminished7
  ['Cdim7', 'diminished7'], ['C°7', 'diminished7'], ['Co7', 'diminished7'],
  ['Cdiminished7', 'diminished7'], ['Cdim7/Eb', 'diminished7'],
  // half_diminished7
  ['Cm7b5', 'half_diminished7'], ['Cm7♭5', 'half_diminished7'], ['Cø', 'half_diminished7'],
  ['Cø7', 'half_diminished7'], ['Cmin7b5', 'half_diminished7'], ['C-7b5', 'half_diminished7'],
  ['Chalfdim', 'half_diminished7'], ['Chalfdim7', 'half_diminished7'],
  ['C half diminished', 'half_diminished7'], ['Cm7(b5)', 'half_diminished7'],
  ['Cø7/Eb', 'half_diminished7'],
  // augmented7 (7#5 maps here — same notes)
  ['Caug7', 'augmented7'], ['C+7', 'augmented7'], ['C7#5', 'augmented7'],
  ['C7+5', 'augmented7'], ['Caugmented7', 'augmented7'],
  // sus2 / sus4
  ['Csus2', 'sus2'], ['Csus 2', 'sus2'], ['Csuspended2', 'sus2'],
  ['Csus', 'sus4'], ['Csus4', 'sus4'], ['Csus 4', 'sus4'], ['Csuspended4', 'sus4'],
  // add9 / add11
  ['Cadd9', 'add9'], ['C(add9)', 'add9'], ['Cadd2', 'add9'], ['Cadd 9', 'add9'],
  ['Cadded9', 'add9'], ['Cadd11', 'add11'], ['C(add11)', 'add11'], ['Cadd 11', 'add11'],
  // minor_major7 — every common spelling incl. Δ glyph
  ['CmMaj7', 'minor_major7'], ['Cm(maj7)', 'minor_major7'], ['C-Δ7', 'minor_major7'],
  ['CmM7', 'minor_major7'], ['Cminmaj7', 'minor_major7'], ['C-maj7', 'minor_major7'],
  ['Cmin(maj7)', 'minor_major7'], ['Cm/maj7', 'minor_major7'], ['CminMaj7', 'minor_major7'],
  ['C-M7', 'minor_major7'], ['CmΔ7', 'minor_major7'],
  // power
  ['C5', 'power'], ['Cpower', 'power'], ['Cpowerchord', 'power'],
  // dominant7sus4 / dominant9sus4
  ['C7sus4', 'dominant7sus4'], ['C7sus', 'dominant7sus4'], ['Cdom7sus4', 'dominant7sus4'],
  ['C9sus4', 'dominant9sus4'], ['C9sus', 'dominant9sus4'],
  // major9 / minor9 / dominant9
  ['Cmaj9', 'major9'], ['CM9', 'major9'], ['CΔ9', 'major9'], ['Cmajor9', 'major9'],
  ['Cm9', 'minor9'], ['Cmin9', 'minor9'], ['C-9', 'minor9'], ['Cminor9', 'minor9'],
  ['C9', 'dominant9'], ['Cdom9', 'dominant9'], ['Cdominant9', 'dominant9'],
  // altered dominants
  ['C7b9', 'dominant7flat9'], ['C7(b9)', 'dominant7flat9'], ['C7♭9', 'dominant7flat9'],
  ['C7#9', 'dominant7sharp9'], ['C7(#9)', 'dominant7sharp9'], ['C7♯9', 'dominant7sharp9'],
  ['C7b5', 'dominant7flat5'], ['C7(b5)', 'dominant7flat5'], ['C7♭5', 'dominant7flat5'],
  ['C7alt', 'dominant7alt'], ['Calt', 'dominant7alt'], ['Calt7', 'dominant7alt'],
  ['Caltered', 'dominant7alt'],
  ['C9#11', 'dominant9sharp11'], ['C9(#11)', 'dominant9sharp11'], ['C9♯11', 'dominant9sharp11'],
  ['C13b9', 'dominant13flat9'], ['C13(b9)', 'dominant13flat9'],
  // 11ths / 13ths
  ['C11', 'dominant11'], ['Cdom11', 'dominant11'],
  ['Cmaj11', 'major11'], ['CM11', 'major11'], ['CΔ11', 'major11'],
  ['Cm11', 'minor11'], ['Cmin11', 'minor11'], ['C-11', 'minor11'],
  ['C13', 'dominant13'], ['Cdom13', 'dominant13'],
  ['Cmaj13', 'major13'], ['CM13', 'major13'], ['CΔ13', 'major13'],
  ['Cm13', 'minor13'], ['Cmin13', 'minor13'], ['C-13', 'minor13'],
  // 6/9 family
  ['C6/9', 'six_nine'], ['C69', 'six_nine'], ['C6add9', 'six_nine'], ['Cmaj6/9', 'six_nine'],
  ['Cm6/9', 'minor_six_nine'], ['Cm69', 'minor_six_nine'], ['Cmin6/9', 'minor_six_nine'],
  ['Cm6add9', 'minor_six_nine'],
  // sus2sus4
  ['Csus2sus4', 'sus2sus4'], ['Csus24', 'sus2sus4'], ['Csus2/4', 'sus2sus4'],
  // augmented_major7
  ['Cmaj7#5', 'augmented_major7'], ['CM7#5', 'augmented_major7'], ['C+maj7', 'augmented_major7'],
  ['CaugMaj7', 'augmented_major7'], ['Cmaj7+', 'augmented_major7'], ['C+M7', 'augmented_major7'],
  // major7flat5 / major7sharp11
  ['Cmaj7b5', 'major7flat5'], ['CM7b5', 'major7flat5'], ['Cmaj7♭5', 'major7flat5'],
  ['Cmaj7#11', 'major7sharp11'], ['CM7#11', 'major7sharp11'], ['Cmaj7(#11)', 'major7sharp11'],
  ['CΔ7#11', 'major7sharp11'],
  // diminished_major7
  ['CdimMaj7', 'diminished_major7'], ['Cdim(maj7)', 'diminished_major7'],
  ['C°maj7', 'diminished_major7'], ['CdimM7', 'diminished_major7'], ['C°M7', 'diminished_major7'],
  ['CoMaj7', 'diminished_major7'],
  // combination altered dominants
  ['C7#5b9', 'dominant7sharp5flat9'], ['C7(#5)(b9)', 'dominant7sharp5flat9'],
  ['Caug7b9', 'dominant7sharp5flat9'], ['C+7b9', 'dominant7sharp5flat9'],
  ['C7b5b9', 'dominant7flat5flat9'], ['C7(b5)(b9)', 'dominant7flat5flat9'],
  ['C7#5#9', 'dominant7sharp5sharp9'], ['C7(#5)(#9)', 'dominant7sharp5sharp9'],
  ['Caug7#9', 'dominant7sharp5sharp9'],
  ['C7b5#9', 'dominant7flat5sharp9'], ['C7(b5)(#9)', 'dominant7flat5sharp9'],
  // trailing '+' on dom7 -> dominant7sharp5 (same notes as augmented7)
  ['C7+', 'dominant7sharp5'],

  // accidental roots / case / unicode
  ['C#m7', 'minor7'], ['Dbm7', 'minor7'], ['F#maj7', 'major7'], ['Gbmaj7', 'major7'],
  ['C♯m7', 'minor7'], ['D♭maj7', 'major7'], ['c#m7', 'minor7'], ['B#dim7', 'diminished7'],
  ['Cbmaj7', 'major7'], ['E#m7', 'minor7'], ['Fbmaj7', 'major7'], ['f#m7b5', 'half_diminished7'],

  // slash chords across qualities
  ['C7/E', 'dominant7'], ['Cmaj7/G', 'major7'], ['Am7/G', 'minor7'],
  ['F#m7b5/C', 'half_diminished7'], ['Bbmaj7/D', 'major7'], ['Cm/Eb', 'minor'],
  ['G7sus4/C', 'dominant7sus4'],

  // parser-level single-word verbal
  ['Cdiminished7', 'diminished7'], ['Caugmented', 'augmented'], ['C minor 7', 'minor7'],
];

// ── 2. NEGATIVE: must NOT parse ────────────────────────────────────────────
const NEGATIVE: string[] = [
  'C0',        // zero is NOT half-diminished — ambiguous, deliberate exclusion
  'Cx',        // garbage suffix
  'Cmaj77',    // invalid double-seven
  'H7',        // German H — unsupported (deliberate)
  'hello world',
  'Cblah',     // garbage word (also guards Cb-root + "lah" leftover)
  'C7b',       // dangling accidental, no degree
  '7',         // no root
  'Zmaj7',     // invalid root letter
  'Czzz', 'C123', 'Cqwerty', 'Cmaj7xyz', 'Ch', 'C55', 'C25',
];

// ── 3. COMPLEX: must still parse (non-null) ────────────────────────────────
// Mostly algorithmic-path chords. WS14 promoted Cmaj9#11 / C7b13 / C7#11 to
// named qualities (now asserted in the CANONICAL block below); the remainder
// still resolve through the lenient algorithmic builder.
const COMPLEX_MUST_PARSE: string[] = [
  'Cmaj7#11', 'G7b9#11', 'Dm9b5', 'C7#9#11', 'Am9', 'Cm11b5', 'C7b9b13',
  'Cadd#11', 'Cm(add9)', 'C7sus4b9', 'Cmaj7#5', 'C6/9', 'Bb7sus4', 'Am(add9)', 'Fmaj13#11',
  'C9sus4', 'C13#11', 'C7#9b13', 'Cm7add11', 'Cmaj7b5', 'Co7', 'C-7b5',
  'D7alt', 'C13b9', 'Cmaj13', 'C7b5#9', 'Cdim(maj7)',
];

describe('chord-search matrix — positive (notation → quality)', () => {
  it.each(POSITIVE)('%s → %s', (notation, expected) => {
    const r = parseChordSymbol(notation);
    expect(r, `"${notation}" should parse`).not.toBeNull();
    expect(r!.quality, `"${notation}" quality`).toBe(expected);
  });
});

describe('chord-search matrix — negative (must NOT parse)', () => {
  it.each(NEGATIVE)('%s → null', (notation) => {
    expect(parseChordSymbol(notation), `"${notation}" should be rejected`).toBeNull();
  });
});

describe('chord-search matrix — complex (algorithmic, must still parse)', () => {
  it.each(COMPLEX_MUST_PARSE)('%s parses', (notation) => {
    expect(parseChordSymbol(notation), `"${notation}" must still parse`).not.toBeNull();
  });
});

describe('chord-search matrix — every ChordQuality reachable by a canonical symbol', () => {
  // The engine defines 50 chord qualities (CHORD_FORMULAS / CHORD_SYMBOLS /
  // CHORD_QUALITY_NAMES all have 50 keys). WS14 closed three taxonomy gaps that
  // previously fell to the algorithmic path: major9sharp11, dominant7sharp11,
  // dominant7flat13. This guards that the parser can produce EACH from at least
  // one symbol (the canonical/primary one). dominant7sharp5 has no distinct
  // primary symbol — bare 7#5 collapses to augmented7 (same notes) — so it is
  // reached via '+'.
  const CANONICAL: Array<[string, ChordQuality]> = [
    ['C', 'major'], ['Cm', 'minor'], ['Cdim', 'diminished'], ['Caug', 'augmented'],
    ['C6', 'major6'], ['Cm6', 'minor6'], ['Cmaj7', 'major7'], ['Cm7', 'minor7'],
    ['C7', 'dominant7'], ['Cdim7', 'diminished7'], ['Cm7b5', 'half_diminished7'],
    ['Caug7', 'augmented7'], ['Csus2', 'sus2'], ['Csus4', 'sus4'], ['Cadd9', 'add9'],
    ['CmMaj7', 'minor_major7'], ['C5', 'power'], ['C7sus4', 'dominant7sus4'],
    ['Cmaj9', 'major9'], ['Cm9', 'minor9'], ['C9', 'dominant9'],
    ['C7b9', 'dominant7flat9'], ['C7#9', 'dominant7sharp9'], ['C7b5', 'dominant7flat5'],
    ['C7+', 'dominant7sharp5'], ['C7alt', 'dominant7alt'], ['C11', 'dominant11'],
    ['Cmaj11', 'major11'], ['Cm11', 'minor11'], ['C9#11', 'dominant9sharp11'],
    ['C13', 'dominant13'], ['Cmaj13', 'major13'], ['Cm13', 'minor13'],
    ['C13b9', 'dominant13flat9'], ['Cadd11', 'add11'], ['C6/9', 'six_nine'],
    ['Cm6/9', 'minor_six_nine'], ['C9sus4', 'dominant9sus4'], ['Csus2sus4', 'sus2sus4'],
    ['Cmaj7#5', 'augmented_major7'], ['Cmaj7b5', 'major7flat5'],
    ['Cmaj7#11', 'major7sharp11'], ['Cdim(maj7)', 'diminished_major7'],
    ['C7#5b9', 'dominant7sharp5flat9'], ['C7b5b9', 'dominant7flat5flat9'],
    ['C7#5#9', 'dominant7sharp5sharp9'], ['C7b5#9', 'dominant7flat5sharp9'],
    // WS14: three closed taxonomy gaps, each now reached by its canonical symbol.
    ['Cmaj9#11', 'major9sharp11'], ['C7#11', 'dominant7sharp11'],
    ['C7b13', 'dominant7flat13'],
  ];

  it.each(CANONICAL)('%s → %s', (symbol, quality) => {
    expect(parseChordSymbol(symbol)?.quality, `${symbol}`).toBe(quality);
  });

  it('covers all 50 engine ChordQuality values via the canonical map', () => {
    // Locks the count so a dropped row is caught. All 50 qualities are reached
    // exactly by their canonical symbol (verified by the audit harness).
    const covered = new Set(CANONICAL.map(([, q]) => q));
    expect(covered.size).toBe(50);
  });
});

describe('chord-search matrix — iOS ordinal autocorrect (º for °)', () => {
  // Typing the degree sign ° (U+00B0) on an iPhone frequently autocorrects to
  // the masculine ordinal º (U+00BA). Both that and the ring operator ∘ (U+2218)
  // normalize to ° so diminished chords still resolve. A leading "m" before the
  // symbol stays a reject (genuinely malformed: "G minor diminished 7").
  const ORDINAL: Array<[string, ChordQuality | null]> = [
    ['Cº', 'diminished'], ['Cº7', 'diminished7'], ['F#º7', 'diminished7'],
    ['Dbº', 'diminished'], ['C∘', 'diminished'], ['C∘7', 'diminished7'],
    ['Gmº7', null],
    // Redundant minor before the half-dim sign (ø already implies minor) resolves;
    // plain minor 7 is untouched.
    ['Bbmø7', 'half_diminished7'], ['Cmø', 'half_diminished7'], ['Bbm7', 'minor7'],
  ];
  it.each(ORDINAL)('%s → %s', (symbol, quality) => {
    expect(parseChordSymbol(symbol)?.quality ?? null, `${symbol}`).toBe(quality);
  });
});
